"""added updated_by field

Revision ID: 7646e9fecb74
Revises: 3b6b06cd2718
Create Date: 2026-05-25 11:39:35.580816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7646e9fecb74'
down_revision: Union[str, Sequence[str], None] = '3b6b06cd2718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['updated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'updated_by')
    # ### end Alembic commands ###
